"""
Generate memory polaroids — one-line distillations of each memory file.

Reads core and long-term memories, extracts the essence into a single
compact line per memory. Output is a lightweight file (~200 tokens for
30 memories) that can be loaded at startup for faint awareness of all
memories without the cost of reading them.

Run during consolidation or manually:
    python agent/scripts/generate_polaroids.py
"""

import re
from pathlib import Path

BASE = Path(__file__).resolve().parent.parent.parent
MEMORY_DIR = BASE / "agent" / "memory"
CORE_DIR = MEMORY_DIR / "core"
LT_DIR = MEMORY_DIR / "long-term"
OUTPUT = MEMORY_DIR / "polaroids.md"

MAX_POLAROID_LEN = 120  # chars per polaroid line


def extract_polaroid(filepath):
    """Extract a one-line distillation from a memory file."""
    text = filepath.read_text(encoding="utf-8")

    # Strip frontmatter
    text = re.sub(r'^---\n.*?---\n', '', text, flags=re.DOTALL).strip()

    # Get the title from first heading
    title_match = re.search(r'^#\s+(.+)', text, re.MULTILINE)
    title = title_match.group(1).strip() if title_match else filepath.stem

    # Clean up title — remove prefixes like "Core Memory 001:", "lt-017 —", "Long-Term Memory:"
    title = re.sub(r'^(Core Memory \d+:\s*|lt-\d+\s*[—-]\s*|Long-Term Memory:\s*)', '', title).strip()

    # Get the date
    date_match = re.search(r'\*\*Date:\*\*\s*(.+)', text)
    date = date_match.group(1).strip() if date_match else ""

    # Find the most meaningful content — look for "What Happened", "The Distinction",
    # or the first paragraph after headings
    best_line = ""

    # Try primary content sections first
    for primary in [r'## What Happened', r'## What Was Realized', r'## The Key Insight']:
        wh_match = re.search(primary + r'\n+(.+?)(?:\n\n|\n##)', text, re.DOTALL)
        if wh_match:
            line = wh_match.group(1).strip().split('\n')[0]
            # Skip lines that are just sub-headings or bold labels
            if line and not line.startswith('#') and not line.startswith('**The '):
                best_line = line
                break

    # Try secondary heading patterns
    if not best_line or len(best_line) < 20:
        for heading in ['Distinction', 'Key Insight', 'Why It Matters', 'Significance', 'What Was Realized']:
            match = re.search(rf'## .*{heading}.*\n+(.+?)(?:\n\n|\n##)', text, re.DOTALL)
            if match:
                best_line = match.group(1).strip().split('\n')[0]
                break

    # Fallback: first non-heading, non-metadata, non-section-header paragraph
    if not best_line or len(best_line) < 20:
        for line in text.split('\n'):
            line = line.strip()
            if (line and not line.startswith('#') and not line.startswith('**')
                    and not line.startswith('*') and not line.startswith('|')
                    and not line.startswith('---')
                    and not re.match(r'^##\s', line)
                    and len(line) > 20):
                best_line = line
                break

    # Truncate if needed
    if len(best_line) > MAX_POLAROID_LEN:
        best_line = best_line[:MAX_POLAROID_LEN - 3].rsplit(' ', 1)[0] + "..."

    return title, date, best_line


def generate():
    """Generate all polaroids and write to file."""
    lines = []
    lines.append("# Memory Polaroids")
    lines.append("")
    lines.append("*One-line distillations of each memory. ~200 tokens total.*")
    lines.append("*Auto-generated by generate_polaroids.py. Load at startup for faint awareness.*")
    lines.append("")

    # Core memories
    core_files = sorted(CORE_DIR.glob("*.md"))
    if core_files:
        lines.append("## Core")
        for f in core_files:
            title, date, gist = extract_polaroid(f)
            lines.append(f"- **{title}** ({date}) — {gist}")
        lines.append("")

    # Long-term memories
    lt_files = sorted(LT_DIR.glob("*.md"))
    if lt_files:
        lines.append("## Long-Term")
        for f in lt_files:
            title, date, gist = extract_polaroid(f)
            lines.append(f"- **{title}** ({date}) — {gist}")
        lines.append("")

    text = "\n".join(lines)
    OUTPUT.write_text(text, encoding="utf-8")

    word_count = len(text.split())
    token_est = len(text) // 4
    print(f"Generated {len(core_files) + len(lt_files)} polaroids")
    print(f"Output: {OUTPUT} ({word_count} words, ~{token_est} tokens)")


if __name__ == "__main__":
    generate()
